name: Lemehost Cookie AutoStart

on:
  schedule:
    - cron: "*/5 * * * *"   # 每 5 分钟
  workflow_dispatch:        # 手动触发

jobs:
  autostart:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      PANEL_BASE: ${{ secrets.PANEL_BASE }}   # 例如 https://lemehost.com 或 https://panel.lemehost.com
      SERVER_IDS: ${{ secrets.SERVER_IDS }}   # 短 UUID，可多个：abc123,def456
      COOKIE: ${{ secrets.COOKIE }}           # 浏览器完整 Cookie：pterodactyl_session=...; XSRF-TOKEN=...; [cf_clearance=...]
      CSRF_TOKEN: ${{ secrets.CSRF_TOKEN }}   # 可选；留空则脚本会从 XSRF-TOKEN Cookie 自动提取
      TIMEOUT: "20"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install --no-cache-dir requests

      - name: Run auto-start
        run: python leme_cookie_autostart.py
