name: Auto Login (Captcha) + Cookie Start

on:
  schedule:
    - cron: "0 */6 * * *"   # 例：每 6 小时刷一次 Cookie（视站点过期策略调整）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PANEL_BASE: ${{ secrets.PANEL_BASE }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      CAP_PROVIDER: "2captcha"
      CAP_API_KEY: ${{ secrets.CAP_API_KEY }}
      SERVER_IDS: ${{ secrets.SERVER_IDS }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --no-cache-dir requests playwright
          python -m playwright install --with-deps chromium

      - name: Login and grab cookie
        id: login
        run: |
          python login_and_dump_cookie.py | tee login.out
          echo "cookie=$(grep '^COOKIE=' login.out | sed 's/^COOKIE=//')" >> "$GITHUB_OUTPUT"

      - name: Install requests for autostart
        run: pip install --no-cache-dir requests

      - name: Auto start via cookie
        env:
          COOKIE: ${{ steps.login.outputs.cookie }}
          CSRF_TOKEN: ""   # 可留空，脚本会从 XSRF-TOKEN cookie 自动提取
        run: |
          python leme_cookie_autostart.py
