name: Lemehost UI-Cookie AutoStart

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  autostart:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    env:
      PANEL_BASE: ${{ secrets.PANEL_BASE }}     # 例如 https://lemehost.com
      SERVER_IDS: ${{ secrets.SERVER_IDS }}     # 短 UUID，例：abc123,def456
      COOKIE: ${{ secrets.COOKIE }}             # 登录后复制的完整 Cookie（含 pterodactyl_session、XSRF-TOKEN、若有 cf_clearance 也需）
      CSRF_TOKEN: ${{ secrets.CSRF_TOKEN }}     # 可选；留空则脚本会自动从 Cookie 或页面 <meta> 解析
      TIMEOUT: "20"
      SERVER_LIST_PATH: "/"                     # 可按需改成你的“Servers”列表页路径
      VIEW_PATH_TEMPLATE: "/server/{id}"        # 如果你的“View”是 /servers/{id}/view，就改为 "/servers/{id}/view"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install --no-cache-dir requests
      - name: Run auto-start (UI flow)
        run: python leme_cookie_ui_autostart.py
