name: Lemehost UI-Cookie AutoStart

on:
  schedule:
    - cron: "*/5 * * * *"  # 每 5 分钟触发
  workflow_dispatch:

jobs:
  autostart:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    env:
      PANEL_BASE: ${{ secrets.PANEL_BASE }}     # https://lemehost.com
      SERVER_IDS: ${{ secrets.SERVER_IDS }}     # 3302157
      COOKIE: ${{ secrets.COOKIE }}             # 完整 cookie
      TIMEOUT: "20"                             # 硬编码超时时间
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install --no-cache-dir requests
      - name: Run auto-renewal
        run: python leme_cookie_ui_autostart.py
